# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20160724_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='category/%Y/%m/%d/', verbose_name='Изображение Категории'),
        ),
    ]
