# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 11:47
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Описание'),
        ),
    ]
