# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 11:50
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20180301_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
