# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-27 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20180301_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descriptionl',
            field=tinymce.models.HTMLField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
