# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-29 13:56
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20180327_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='descriptionl',
        ),
        migrations.AddField(
            model_name='product',
            name='complects',
            field=tinymce.models.HTMLField(default=True, verbose_name='Комплектация'),
        ),
        migrations.AddField(
            model_name='product',
            name='docs',
            field=tinymce.models.HTMLField(default=True, verbose_name='Документация'),
        ),
        migrations.AddField(
            model_name='product',
            name='opisanie',
            field=tinymce.models.HTMLField(default=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=tinymce.models.HTMLField(default=True, verbose_name='Фотогалерея'),
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=tinymce.models.HTMLField(default=True, verbose_name='Видеообзоры'),
        ),
    ]
