# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20180329_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='DopProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение товара')),
                ('opisanie', tinymce.models.HTMLField(default=True, verbose_name='Описание')),
                ('tech', tinymce.models.HTMLField(default=True, verbose_name='Технические характеристики')),
                ('complects', tinymce.models.HTMLField(default=True, verbose_name='Комплектация')),
                ('docs', tinymce.models.HTMLField(default=True, verbose_name='Документация')),
                ('photo', tinymce.models.HTMLField(default=True, verbose_name='Фотогалерея')),
                ('video', tinymce.models.HTMLField(default=True, verbose_name='Видеообзоры')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('stock', models.PositiveIntegerField(verbose_name='На складе')),
                ('available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dopproducts', to='shop.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Доптовар',
                'verbose_name_plural': 'Доптовары',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tech',
            field=tinymce.models.HTMLField(default=True, verbose_name='Технические характеристики'),
        ),
        migrations.AlterIndexTogether(
            name='dopproduct',
            index_together=set([('id', 'slug')]),
        ),
    ]
