# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-05 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20180404_1319'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='dopproduct',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='dopproduct',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='dopproduct',
            field=models.BooleanField(default=False, verbose_name='Допоборудование'),
        ),
        migrations.DeleteModel(
            name='DopProduct',
        ),
    ]
