# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-07 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20180405_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mass',
            field=models.IntegerField(default=100, verbose_name='Вес'),
        ),
    ]
