# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-21 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_mass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['slug'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.FloatField(default=0.003, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default=True, max_length=200, verbose_name='Артикул'),
        ),
    ]
