# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-10 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180504_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(max_length=120, null=True, verbose_name='Доставка'),
        ),
    ]
