# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-11 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180510_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ship_price',
            field=models.IntegerField(blank=True, default=1, verbose_name='Цена доставки'),
            preserve_default=False,
        ),
    ]
