# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-11 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_ship_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ship_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена доставки'),
        ),
    ]
