# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-14 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180511_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pageid',
            field=models.CharField(db_index=True, default=6476409099, max_length=200, verbose_name='Страница заказа'),
            preserve_default=False,
        ),
    ]
