# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-15 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20180604_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_comment',
            field=models.TextField(default='', verbose_name='Коментарий администратора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Принят'), ('confirmed', 'Подтвержден'), ('processing', 'Обрабатывается'), ('sended', 'Отправлен'), ('canceled', 'Отменен')], default='new', max_length=64, verbose_name='Статус'),
        ),
    ]
