# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-19 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20180615_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='admin_comment',
            field=models.TextField(blank=True, verbose_name='Коментарий администратора'),
        ),
    ]
